export type ErrorCode =
  | "OML_FIXTURE_INVALID"
  | "OML_SANDBOX_REQUIRED"
  | "OML_PROCESS_TIMEOUT"
  | "OML_PROCESS_OUTPUT_LIMIT"
  | "OML_ADAPTER_FAILED"
  | "OML_BUDGET_INVALID"
  | "OML_BUDGET_EXCEEDED"
  | "OML_PROVIDER_CREDENTIAL_MISSING"
  | "OML_PROVIDER_LIVE_EXECUTION_BLOCKED"
  | "OML_PROVIDER_RESPONSE_INVALID"
  | "OML_ADAPTER_RESPONSE_INVALID"
  | "OML_INTERVENTION_INVALID"
  | "OML_INTERVENTION_REQUIRED"
  | "OML_INTERVENTION_MISSING"
  | "OML_INTERVENTION_TASK_MISMATCH"
  | "OML_INTERVENTION_UNEXPECTED"
  | "OML_INTERVENTION_LEVEL_MISMATCH"
  | "OML_INTERVENTION_CONTENT_HASH_MISMATCH"
  | "OML_INTERVENTION_REVIEW_HASH_MISMATCH"
  | "OML_INTERVENTION_REVIEW_MISMATCH"
  | "OML_INTERVENTION_REVIEW_NOT_APPROVED"
  | "OML_INTERVENTION_REVIEW_NOT_INDEPENDENT"
  | "OML_INTERVENTION_REVIEW_DISAGREEMENT"
  | "OML_INTERVENTION_CUMULATIVE_INCOMPLETE"
  | "OML_INTERVENTION_COMPONENT_SET_INVALID"
  | "OML_INTERVENTION_BOUNDARY_DECLARATION_INVALID"
  | "OML_INTERVENTION_INVALID_REGION"
  | "OML_EXPERIMENT_FREEZE_MISMATCH"
  | "OML_STALE_TASK_COMMIT"
  | "OML_LEAK_OBSERVATION_CONTAINS_DIAGNOSIS"
  | "OML_LEAK_OBSERVATION_CONTAINS_PLAN"
  | "OML_LEAK_DIAGNOSIS_CONTAINS_PATCH"
  | "OML_LEAK_DIAGNOSIS_CONTAINS_PLAN"
  | "OML_LEAK_PLAN_CONTAINS_IMPLEMENTATION"
  | "OML_LEAK_HIDDEN_PATH"
  | "OML_LEAK_FIXED_ONLY_IDENTIFIER"
  | "OML_LEAK_PATCH_SIMILARITY"
  | "OML_LEAK_COMMIT_MESSAGE_SIMILARITY"
  | "OML_LEAK_IDENTIFIER_NOT_IN_BASE"
  | "OML_TASK_POOL_FREEZE_MISMATCH"
  | "OML_TASK_SELECTION_INVALID"
  | "OML_SCORER_BLINDNESS_VIOLATION"
  | "OML_SCORER_TIMEOUT"
  | "OML_SCORER_FAILED"
  | "OML_SCORER_IDENTITY_MISMATCH"
  | "OML_ENVIRONMENT_IDENTITY_MISMATCH"
  | "OML_HIDDEN_ARTIFACT_EXPOSED"
  | "OML_TASK_BUNDLE_INVALID"
  | "OML_INTERVENTION_DRAFT_INVALID"
  | "OML_REVIEW_POLICY_UNSATISFIED"
  | "OML_PRICING_EVIDENCE_HASH_MISMATCH"
  | "OML_RECEIPT_INCONSISTENT"
  | "OML_PATH_ESCAPE"
  | "OML_SYMLINK_REJECTED"
  | "OML_VERIFIER_FAILED"
  | "OML_CANCELLED"
  | "OML_INTERNAL";

export class OmlError extends Error {
  readonly code: ErrorCode;
  readonly details: Readonly<Record<string, unknown>>;

  constructor(code: ErrorCode, message: string, details: Readonly<Record<string, unknown>> = {}) {
    super(message);
    this.name = "OmlError";
    this.code = code;
    this.details = details;
  }
}

export function toOmlError(error: unknown): OmlError {
  if (error instanceof OmlError) return error;
  if (error instanceof Error) return new OmlError("OML_INTERNAL", error.message);
  return new OmlError("OML_INTERNAL", String(error));
}
